name: Run curieconf client Javascript (Jest) tests

on:
  pull_request:
    paths:
      - "curiefense/ui/**"
      - ".github/workflows/run-curieconf-client-tests.yml"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: |
          cd "$GITHUB_WORKSPACE/curiefense/ui"
          npm i

      - name: Run unit tests
        run: |
          cd "$GITHUB_WORKSPACE/curiefense/ui"
          npm run coverage
